#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

export PATH="$PATH:$HOME/bin"
export EDITOR="vim"
export SUDO_EDITOR=/usr/bin/vim
export FZF_DEFAULT_OPTS='--height 60% --layout=reverse --border'





